apiVersion: v1
kind: Pod
spec:
  containers:
    - name: docker
      image: docker:18.06.1
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
    - name: kubectl
      image: bitnami/kubectl:latest
      command: ["/bin/sh", "-c", "sleep 99d"]
      imagePullPolicy: Always
      tty: true
      securityContext:
        runAsUser: 0
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
