# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: vue-app-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: vue-app
#   template:
#     metadata:
#       labels:
#         app: vue-app
#     spec:
#       containers:
#         - name: vue-app-container
#           image: vue-app
#           ports:
#             - containerPort: 8080
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
        - name: vue-app-container
          image: vue-app
          ports:
            - containerPort: 8080
        - name: docker
          image: docker:18.06.1
          command: ["tail", "-f", "/dev/null"]
          imagePullPolicy: Always
          volumeMounts:
            - name: docker
              mountPath: /var/run/docker.sock # We use the k8s host docker engine
      volumes:
        - name: docker
          hostPath:
            path: /var/run/docker.sock
